name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'   # یہاں وہ ورژن ڈالیں جو آپ use کر رہے ہیں
          channel: 'stable'

      # Step 3: Check Flutter version
      - name: Flutter Version
        run: flutter --version

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 5: Run analyzer (optional but recommended)
      - name: Run Flutter Analyze
        run: flutter analyze

      # Step 6: Run tests
      - name: Run Flutter Tests
        run: flutter test
