name: Build APK with Android Fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        
    - name: Create Android Directory Structure
      run: |
        mkdir -p android/app/src/main/res/values
        mkdir -p android/app/src/main/res/drawable
        mkdir -p android/app/src/main/kotlin/com/example/shuaib_islamic_app
        
    - name: Create AndroidManifest.xml
      run: |
        cat > android/app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.example.shuaib_islamic_app">
            
            <uses-permission android:name="android.permission.INTERNET" />
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
            
            <application
                android:label="Shuaib Islamic App"
                android:name="${applicationName}"
                android:icon="@mipmap/ic_launcher"
                android:allowBackup="false"
                android:theme="@style/LaunchTheme">
                
                <activity
                    android:name=".MainActivity"
                    android:exported="true"
                    android:launchMode="singleTop"
                    android:theme="@style/LaunchTheme"
                    android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                    android:hardwareAccelerated="true"
                    android:windowSoftInputMode="adjustResize">
                    
                    <meta-data
                        android:name="io.flutter.embedding.android.NormalTheme"
                        android:resource="@style/NormalTheme" />
                        
                    <meta-data
                        android:name="io.flutter.embedding.android.SplashScreenDrawable"
                        android:resource="@drawable/launch_background" />
                        
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
                
                <meta-data
                    android:name="flutterEmbedding"
                    android:value="2" />
            </application>
        </manifest>
        EOF
        
    - name: Create styles.xml
      run: |
        cat > android/app/src/main/res/values/styles.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
                <item name="android:windowBackground">@drawable/launch_background</item>
            </style>
            
            <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
                <item name="android:windowBackground">@android:color/white</item>
            </style>
        </resources>
        EOF
        
    - name: Create launch_background.xml
      run: |
        cat > android/app/src/main/res/drawable/launch_background.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
            <item android:drawable="@android:color/white" />
        </layer-list>
        EOF
        
    - name: Create MainActivity.kt
      run: |
        cat > android/app/src/main/kotlin/com/example/shuaib_islamic_app/MainActivity.kt << 'EOF'
        package com.example.shuaib_islamic_app
        import io.flutter.embedding.android.FlutterActivity
        class MainActivity: FlutterActivity() {
        }
        EOF

    - name: Create build.gradle for app
      run: |
        cat > android/app/build.gradle << 'EOF'
        def localProperties = new Properties()
        def localPropertiesFile = rootProject.file('local.properties')
        if (localPropertiesFile.exists()) {
            localPropertiesFile.withReader('UTF-8') { reader ->
                localProperties.load(reader)
            }
        }

        def flutterRoot = localProperties.getProperty('flutter.sdk')
        if (flutterRoot == null) {
            throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
        }

        def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
        if (flutterVersionCode == null) {
            flutterVersionCode = '1'
        }

        def flutterVersionName = localProperties.getProperty('flutter.versionName')
        if (flutterVersionName == null) {
            flutterVersionName = '1.0'
        }

        apply plugin: 'com.android.application'
        apply plugin: 'kotlin-android'
        apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

        android {
            namespace "com.example.shuaib_islamic_app"
            compileSdkVersion 34

            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }

            kotlinOptions {
                jvmTarget = '1.8'
            }

            sourceSets {
                main.java.srcDirs += 'src/main/kotlin'
            }

            defaultConfig {
                applicationId "com.example.shuaib_islamic_app"
                minSdkVersion 21
                targetSdkVersion 34
                versionCode flutterVersionCode.toInteger()
                versionName flutterVersionName
            }

            buildTypes {
                release {
                    signingConfig signingConfigs.debug
                }
            }
        }

        flutter {
            source '../..'
        }

        dependencies {
            implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
        }
        EOF

    - name: Create build.gradle for android
      run: |
        cat > android/build.gradle << 'EOF'
        buildscript {
            ext.kotlin_version = '1.7.10'
            repositories {
                google()
                mavenCentral()
            }

            dependencies {
                classpath 'com.android.tools.build:gradle:7.3.0'
                classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            }
        }

        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }

        rootProject.buildDir = '../build'
        subprojects {
            project.buildDir = "${rootProject.buildDir}/${project.name}"
        }
        subprojects {
            project.evaluationDependsOn(':app')
        }

        tasks.register("clean", Delete) {
            delete rootProject.buildDir
        }
        EOF

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
