name: Build APK with New Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'

    - name: Create New Flutter Project
      run: |
        flutter create --org com.example shuaib_islamic_app_new
        cp -r lib/* shuaib_islamic_app_new/lib/
        cp pubspec.yaml shuaib_islamic_app_new/
        cd shuaib_islamic_app_new

    - name: Install Dependencies
      run: |
        cd shuaib_islamic_app_new
        flutter pub get

    - name: Build APK
      run: |
        cd shuaib_islamic_app_new
        flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: shuaib_islamic_app_new/build/app/outputs/flutter-apk/app-release.apk
