name: Flutter CI & Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'   # اپنا version یہاں لکھیں
          channel: 'stable'

      # Step 3: Verify Flutter version
      - name: Flutter Version
        run: flutter --version

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 5: Run analyzer
      - name: Run Flutter Analyze
        run: flutter analyze

      # Step 6: Run tests (skip if no test files)
      - name: Run Flutter Tests
        if: ${{ hashFiles('test/**') != '' }}
        run: flutter test

      # Step 7: Build APK (release mode)
      - name: Build APK
        run: flutter build apk --release

      # Step 8: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
